FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY otel_instrumentation.py .
COPY db.py .

RUN mkdir -p /data

EXPOSE 8082

CMD ["python", "db.py"]

